import { HomepageStats, Product, NavItem, Page, Testimonial, FAQ } from "./types"

export const mockStats: HomepageStats = {
  id: "1",
  clients: 5000,
  uptime: 99.9,
  support: 24,
  locations: 10,
  updated_at: new Date().toISOString(),
}

export const mockProducts: Product[] = [
  {
    id: "p1",
    name: "Starter Shared Hosting",
    description: "Perfect for small websites and blogs",
    price: 2.99,
    billing_period: "/mo",
    sku: "SH-STARTER",
    category: "hosting",
    icon: "Server",
    order_url: "https://billing.qazi.host/cart.php?a=add&pid=1",
    is_featured: true,
    features: ["5 GB NVMe SSD", "Unlimited Bandwidth", "Free SSL Certificate", "cPanel Access", "24/7 WhatsApp Support"],
    Built_at: new Date().toISOString(),
  },
  {
    id: "p2",
    name: "Business Shared Hosting",
    description: "Ideal for growing businesses",
    price: 5.99,
    billing_period: "/mo",
    sku: "SH-BUSINESS",
    category: "hosting",
    icon: "Server",
    order_url: "https://billing.qazi.host/cart.php?a=add&pid=2",
    is_featured: true,
    features: ["20 GB NVMe SSD", "Unlimited Bandwidth", "Free SSL Certificate", "cPanel Access", "Daily Backups", "Priority Support"],
    Built_at: new Date().toISOString(),
  },
  {
    id: "p3",
    name: "cPanel License",
    description: "Official cPanel/WHM license for your server",
    price: 15.99,
    billing_period: "/mo",
    sku: "LIC-CPANEL",
    category: "license",
    icon: "KeyRound",
    order_url: "https://billing.qazi.host/cart.php?a=add&pid=10",
    is_featured: false,
    features: ["Official License", "Auto Renewal", "Instant Activation", "All cPanel Features"],
    Built_at: new Date().toISOString(),
  },
  {
    id: "p4",
    name: "Dedicated Server - Intel Xeon",
    description: "High-performance dedicated server",
    price: 89.99,
    billing_period: "/mo",
    sku: "DS-XEON-01",
    category: "dedicated",
    icon: "HardDrive",
    order_url: "https://billing.qazi.host/cart.php?a=add&pid=20",
    is_featured: true,
    features: ["Intel Xeon E-2236", "32 GB DDR4 RAM", "2x 480GB SSD", "1 Gbps Port", "Full Root Access", "DDoS Protection"],
    Built_at: new Date().toISOString(),
  },
  {
    id: "p5",
    name: "Server Installation Service",
    description: "Complete server setup and configuration",
    price: 29.99,
    billing_period: "one-time",
    sku: "SVC-INSTALL",
    category: "service",
    icon: "Wrench",
    order_url: "https://billing.qazi.host/cart.php?a=add&pid=30",
    is_featured: false,
    features: ["OS Installation", "Control Panel Setup", "Security Hardening", "DNS Configuration", "SSL Installation"],
    Built_at: new Date().toISOString(),
  },
]

export const mockNavItems: NavItem[] = [
  {
    id: "n1",
    label: "Hosting",
    url: "/hosting",
    sort_order: 0,
    parent_id: null,
    icon: null,
    description: null,
    children: [
      { id: "n1a", label: "Shared Hosting", url: "/shared-hosting", sort_order: 0, parent_id: "n1", icon: "Server", description: "Affordable hosting for websites" },
      { id: "n1b", label: "Reseller Hosting", url: "/reseller-hosting", sort_order: 1, parent_id: "n1", icon: "Users", description: "Start your own hosting business" },
      { id: "n1c", label: "VPS Hosting", url: "/vps-hosting", sort_order: 2, parent_id: "n1", icon: "Cloud", description: "Virtual private servers with root access" },
    ],
  },
  {
    id: "n2",
    label: "Dedicated Servers",
    url: "/dedicated-servers",
    sort_order: 1,
    parent_id: null,
    icon: null,
    description: null,
    children: [],
  },
  {
    id: "n3",
    label: "Licenses",
    url: "/licenses",
    sort_order: 2,
    parent_id: null,
    icon: null,
    description: null,
    children: [
      { id: "n3a", label: "cPanel License", url: "/cpanel-license", sort_order: 0, parent_id: "n3", icon: "KeyRound", description: "Official cPanel/WHM license" },
      { id: "n3b", label: "Plesk License", url: "/plesk-license", sort_order: 1, parent_id: "n3", icon: "KeyRound", description: "Plesk Obsidian license" },
      { id: "n3c", label: "LiteSpeed License", url: "/litespeed-license", sort_order: 2, parent_id: "n3", icon: "Zap", description: "LiteSpeed Web Server license" },
      { id: "n3d", label: "CloudLinux License", url: "/cloudlinux-license", sort_order: 3, parent_id: "n3", icon: "Shield", description: "CloudLinux OS license" },
    ],
  },
  {
    id: "n4",
    label: "Services",
    url: "#",
    sort_order: 3,
    parent_id: null,
    icon: null,
    description: null,
    children: [
      { id: "n4a", label: "Server Installation", url: "/server-installation", sort_order: 0, parent_id: "n4", icon: "Wrench", description: "Complete server setup" },
      { id: "n4b", label: "Web Development", url: "/web-development", sort_order: 1, parent_id: "n4", icon: "Code", description: "Custom web development" },
      { id: "n4c", label: "Web Designing", url: "/web-designing", sort_order: 2, parent_id: "n4", icon: "Palette", description: "Professional web design" },
    ],
  },
]

export const mockPages: Page[] = [
  {
    id: "pg1",
    title: "About Us",
    slug: "about",
    meta_description: "Learn about Qazi.Host - Premium hosting and infrastructure provider.",
    content: "# About Qazi.Host\n\nWe are a premium hosting and infrastructure provider...",
    Built_at: new Date().toISOString(),
  },
  {
    id: "pg2",
    title: "Terms of Service",
    slug: "terms",
    meta_description: "Qazi.Host terms of service and acceptable use policy.",
    content: "# Terms of Service\n\nBy using our services, you agree to...",
    Built_at: new Date().toISOString(),
  },
]

export const mockTestimonials: Testimonial[] = [
  {
    id: "t1",
    client_name: "Ahmed Khan",
    role: "Web Developer",
    review_text: "Qazi.Host has been an amazing experience. The support is lightning fast and the uptime is incredible!",
    initials: "AK",
    stars: 5,
    Built_at: new Date().toISOString(),
  },
  {
    id: "t2",
    client_name: "Sarah Williams",
    role: "E-commerce Store Owner",
    review_text: "Migrated from another provider and couldn't be happier. The dedicated servers are a beast!",
    initials: "SW",
    stars: 5,
    Built_at: new Date().toISOString(),
  },
  {
    id: "t3",
    client_name: "Muhammad Ali",
    role: "Agency Owner",
    review_text: "Great reseller hosting. I run 50+ client sites and never had a single issue with uptime.",
    initials: "MA",
    stars: 4,
    Built_at: new Date().toISOString(),
  },
]

export const mockFAQs: FAQ[] = [
  { id: "f1", question: "What payment methods do you accept?", answer: "We accept credit/debit cards, PayPal, cryptocurrency, and bank transfers. Contact us via WhatsApp for local payment options.", sort_order: 0 },
  { id: "f2", question: "Do you offer DMCA ignored hosting?", answer: "Yes, our offshore hosting plans are DMCA ignored. Your content is safe with us.", sort_order: 1 },
  { id: "f3", question: "How fast is your support?", answer: "Our WhatsApp support is available 24/7 with an average response time under 5 minutes.", sort_order: 2 },
  { id: "f4", question: "Can I upgrade my plan later?", answer: "Absolutely! You can upgrade or downgrade your plan at any time from your client area. The price difference will be prorated.", sort_order: 3 },
]
